### ISSUE TITLE
declaration for TypeScript

### ISSUE THREAD

**Issue by kamakiri01** [davidbkemp/jsqubits#25]
Hello, 
Since I want to use jsqubits with TypeScript, I wrote d.ts of jsqubits.

https://github.com/qramana/jsqubits.d.ts

This type definition mostly covers the I/F of jsqubits.

I'm already happy, but I think it would be more useful if this was published npm.

May I create PR of this for DefinitelyTyped? (DefinitelyTyped is TypeScript d.ts repository)

This d.ts maybe named @types/jsqubits when publish.
This name is same as your library.
If you do not want this publish, please let me know.

**Comment by davidbkemp** [comment]
Thank you for asking.

I currently have no big plans for jsqubits.
I think it will be OK for you to publish your d.ts as `@types/jsqubits`.

I think the main risk is that one day you may no longer be able to maintain `qramana/jsqubits.d.ts` or perhaps no longer want to maintain it.  If and when that ever happens I guess I will have two options: either you grant me commit rights to `qramana/jsqubits.d.ts` and publish rights to the npm `@types/jsqubits`, or I publish the d.ts as part of jsqubits itself.

**Comment by kamakiri01** [comment]
Thank you for reply.
I'm glad to receive your kind answer.

Your concerns about risk are correct.
I can give you the commit and publish rights of `qramana/jsqubits.d.ts`, but I think it is better to publish by including d.ts in jsqubits. Then the users depend on only one jsqubits package. I think that is good for the convenience of the users.

If so, I create a PR that add d.ts to jsqubits.
Also, if you think that it is good that I maintain d.ts from now on directly, grant me commit rights.

**Comment by davidbkemp** [comment]
Sorry about my slow response. I think at this stage I would prefer to keep the TypeScript declarations separate.

I will be very happy for you to publish your work to `@types/jsqubits`.

I can add links to `@types/jsqubits` and `qramana/jsqubits.d.ts` from within the jsqubits README if you like. Perhaps one day, if sufficient users of jsqubits want the TypeScript declarations, then we could combine them.

**Comment by kamakiri01** [comment]
Sorry if my offer was putting a strain you. That is not my wish.
I'm glad you considered this issue.

I will start preparing to publish  `@types/jsqubits.d.ts`.
Thank you for allowing publish this name.

When `@types/jsqubits.d.ts` is successfully published, I will contact you.
Then I would be happy if you added a link for TypeScript users to the jsqubits README.

I hope that there are a lot of jsqubits users in the future. (and TypeScript!)

thx.

**Comment by kamakiri01** [comment]
Hello,
I have published `@types/jsqubits` successfully.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36805
https://www.npmjs.com/package/@types/jsqubits

We can use type definition, after `$ npm install @types/jsqubits` .

If possible, add links and install command to jsqubits README, so I will be very happy.

**Comment by davidbkemp** [comment]
OK, I’ll look at it this weekend.

**Comment by davidbkemp** [comment]
Released v1.1.1 with README including links to TypeScript repos.
Thanks for doing the TypeScript work @kamakiri01 
I hope you find jsqubits useful.

**Comment by kamakiri01** [comment]
I found jsqubits v1.1.1 on npm. Thanks!
